In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data=pd.read_csv("emails.csv")
data.head(5)

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [14]:
data["text"]=data['text'].apply(lambda x:x.replace("Subject:","").strip())
data.drop_duplicates(inplace=True)
data.head(10)

                                                text  spam
0  : naturally irresistible your corporate identi...     1
1  : the stock trading gunslinger  fanny is merri...     1
2  : unbelievable new homes made easy  im wanting...     1
3  : 4 color printing special  request additional...     1
4  : do not have money , get software cds from he...     1
5  : great nnews  hello , welcome to medzonline s...     1
6  : here ' s a hot play in motion  homeland secu...     1
7  : save your money buy getting this thing here ...     1
8  : undeliverable : home based business for grow...     1
9  : save your money buy getting this thing here ...     1

In [15]:
x=data['text']
y=data['spam']

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
x_test,x_train,y_test,y_tarin=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)